import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/layout/NavigationBar";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kaligrafi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`max-w-screen w-screen overflow-x-hidden overflow-x-clip bg-[#FAF1EA] ${inter.className}`}
      >
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
