import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/layout/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kaligrafi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#FAF1EA] ${inter.className}`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
